server:
  port: 2333
  address: 127.0.0.1   # allow remote bot to connect (VPS)

plugins:
  youtube:
    enabled: true            # allow YouTube source
    allowSearch: true        # allow "ytsearch:" and "ytmsearch:"
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED

lavalink:
  plugins:
    # Replace VERSION with the current version as shown by the Releases tab or a long commit hash for snapshots.
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.16.0"
      snapshot: false # Set to true if you want to use a snapshot version.

  server:
    password: "yourownpassword"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6

logging:
  level:
    root: INFO
    lavalink: INFO

metrics:
  prometheus:
    enabled: false